//
//  QuotesData.swift
//  TestApp
//
//  Created by Raja Sushil Adhikari on 19/08/2025.
//

import Foundation

extension Quote {
    static let spiritualQuotes: [Quote] = [
        .init(title: "", description: "You are what you believe in. You become that which you believe you can become.", author: ""),
        .init(title: "", description: "Change is the law of the universe. You can be a millionaire, or a pauper in an instant.", author: ""),
        .init(title: "", description: "You have the right to perform your duties, but you are not entitled to the fruits of your actions.", author: ""),
        .init(title: "", description: "Man is made by his belief. As he believes, so he is.", author: ""),
        .init(title: "", description: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.", author: ""),
        .init(title: "", description: "When consciousness is unified, however, all vain anxiety is left behind. There is no cause for worry, whether things go well or ill.", author: ""),
        .init(title: "", description: "It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.", author: ""),
        .init(title: "", description: "Happiness is a state of mind and has nothing to do with the external world.", author: ""),
        .init(title: "", description: "Make it easy for yourself. Get organized and live in the moment. Your day-to-day activities should not steal your happiness.", author: ""),
        .init(title: "", description: "A person can rise through the efforts of his own mind; or draw himself down, in the same manner. Because each person is his own friend or enemy.", author: ""),
        .init(title: "", description: "To refrain from selfish acts is one kind of renunciation, called sannyasa; to renounce the fruit of action is another, called Tyaga.", author: ""),
        .init(title: "", description: "There is neither this world nor the world beyond nor happiness for the one who doubts.", author: ""),
        .init(title: "", description: "No one who does good work will ever come to a bad end, either here or in the world to come.", author: ""),
        .init(title: "", description: "Whatever happened, happened for the good. Whatever is happening, is happening for the good. Whatever will happen, will also happen for the good.", author: ""),
        .init(title: "", description: "Cultivate vigour, patience, will, purity; avoid malice and pride.", author: ""),
        .init(title: "", description: "The struggle for self-mastery that every human being must wage if he or she is to emerge from life victorious.", author: ""),
        .init(title: "", description: "His judgement will be better and his vision clear if he is not emotionally entangled in the outcome of what he does.", author: ""),
        .init(title: "", description: "He who experiences the unity of life sees his own Self in all beings, and all beings in his own Self, and looks on everything with an impartial eye.", author: ""),
        .init(title: "", description: "We behold what we are, and we are what we behold.", author: ""),
        .init(title: "", description: "Feelings of heat and cold, pleasure and pain, are caused by the contact of the senses with their objects. They come and they go, never lasting long. You must accept them.", author: ""),
        .init(title: "", description: "Karmanyaevadhikarste ma Faleshu Kadachan. That is, your right is only in doing work, do not worry about the fruit.", author: ""),
        .init(title: "", description: "Yoga: Karmasu Kaushalam. That is, yoga is skillful in deeds.", author: ""),
        .init(title: "", description: "What happened happened to the good; what is happening is happening for good; what will happen will also be for good.", author: ""),
        .init(title: "", description: "The soul is immortal, immortal and indestructible. That is, the soul cannot be burned, it cannot be cut.", author: ""),
        .init(title: "", description: "Anger leads to confusion and intellect is destroyed by confusion.", author: ""),
        .init(title: "", description: "Man is created by his faith. That is, as he believes, he becomes.", author: ""),
        .init(title: "", description: "The person who doubts does not find happiness in this world nor in the Hereafter.", author: ""),
        .init(title: "", description: "The restraint of the senses is true knowledge.", author: ""),
        .init(title: "", description: "By getting rid of ego, a person can recognize his true nature.", author: ""),
        .init(title: "", description: "To practice one's religion is the greatest religion.", author: ""),
        .init(title: "", description: "Everyone is bound by their duties. That is, perform your duties, this is the best path.", author: ""),
        .init(title: "", description: "For the one who subdues the mind, the mind is a friend.", author: ""),
        .init(title: "", description: "Success and failure, profit and loss, happiness and sorrow should remain the same.", author: ""),
        .init(title: "", description: "The struggle is life. Meaning- Every challenge is the medium of self-development.", author: ""),
        .init(title: "", description: "The person who sees from the point of view of knowledge sees the same soul in every soul.", author: ""),
        .init(title: "", description: "Everything in the world is fleeting. Meaning: Only the soul is permanent.", author: ""),
        .init(title: "", description: "Whatever you have is the fruit of your deeds.", author: ""),
        .init(title: "", description: "A true yogi is one who is stable in peace of mind.", author: ""),
        .init(title: "", description: "He who lives his life by dedication and devotion, he attains the Supreme Soul.", author: ""),
        .init(title: "", description: "Free from fear and follow the path of truth.", author: ""),
        .init(title: "", description: "Self-knowledge is the way of salvation.", author: ""),
        .init(title: "", description: "Knowledge is the true light.", author: ""),
        .init(title: "", description: "Everyone is responsible for their actions.", author: ""),
        .init(title: "", description: "No one can kill the soul, no one can touch it.", author: ""),
        .init(title: "", description: "Nature is governed by its own laws.", author: ""),
        .init(title: "", description: "The one who walks on the path of truth never loses.", author: ""),
        .init(title: "", description: "All living beings are part of the same spirit.", author: ""),
        .init(title: "", description: "Avoid overdoing anything.", author: ""),
        .init(title: "", description: "To remain stable in happiness, sorrow, profit and loss is true yoga.", author: ""),
        .init(title: "", description: "The soul is immortal, so there is no need to be afraid of death.", author: ""),
        .init(title: "", description: "A knowledgeable person considers both knowledge and action to be equal. Life is successful only by the balance of knowledge and action.", author: ""),
        .init(title: "", description: "He who gives up all desires and is freed from the spirit of 'I' and 'my', he attains peace.", author: ""),
        .init(title: "", description: "He who works free from the desire for karma is a true yogi.", author: ""),
        .init(title: "", description: "Human beings become great through their actions.", author: ""),
        .init(title: "", description: "It is true knowledge to see friends and enemies in equal terms.", author: ""),
        .init(title: "", description: "Perform your duties, without fear or doubt.", author: ""),
        .init(title: "", description: "Whoever offers me with devotion – a leaf, a flower, a fruit or water – I accept that.", author: ""),
        .init(title: "", description: "Not everyone can escape the consequences of their actions.", author: ""),
        .init(title: "", description: "Conquering oneself is the greatest victory.", author: ""),
        .init(title: "", description: "The person who controls anger and desires is the true yogi.", author: ""),
        .init(title: "", description: "To respect everyone equally is true devotion.", author: ""),
        .init(title: "", description: "Change is the law of the world. What is yours today, tomorrow will be someone else's.", author: ""),
        .init(title: "", description: "The person who condemns others is ignorant.", author: ""),
        .init(title: "", description: "The way to salvation from sorrow is to know the soul.", author: ""),
        .init(title: "", description: "The man who keeps himself calm and restrained is the true wise.", author: ""),
        .init(title: "", description: "Know the truth within yourself; this is the way of salvation.", author: ""),
        .init(title: "", description: "Excessive attachment is the cause of grief.", author: ""),
        .init(title: "", description: "Look at the part of God in all living beings.", author: ""),
        .init(title: "", description: "The one who sees success and failure in equal terms is the true yogi.", author: ""),
        .init(title: "", description: "The purpose of life is to know the soul and be one with Brahman.", author: ""),
        .init(title: "", description: "Make good use of the time you have.", author: ""),
        .init(title: "", description: "The work done with devotion and faith is fruitful.", author: ""),
        .init(title: "", description: "Do not compare the actions of others to yourself; follow your religion.", author: ""),
        .init(title: "", description: "Publish the soul with the light of knowledge.", author: ""),
        .init(title: "", description: "Beliefing in yourself is the key to success.", author: ""),
        .init(title: "", description: "For a person who is always doubtful, there is no happiness in this world or anywhere else.", author: ""),
        .init(title: "", description: "When a person finds joy in his work, he attains perfection.", author: ""),
        .init(title: "", description: "A person has to control the intellect and mind to control his senses.", author: ""),
        .init(title: "", description: "A person always curses his destiny, knowing that even higher than luck is his work in his own hands.", author: ""),
        .init(title: "", description: "No one in this world is completely right, so make good relations with people by looking at the goodness of them.", author: ""),
        .init(title: "", description: "When our mind is weak, circumstances become a problem and when our mind is hard, circumstances become a challenge. When our mind is strong, circumstances become opportunities.", author: ""),
        .init(title: "", description: "If you learn something from your mistakes, mistakes are made by the stairs and if you do not learn, then the mistakes are oceans, the decision is yours to climb or sink.", author: ""),
        .init(title: "", description: "The quieter he can use his intellect as deeply.", author: ""),
        .init(title: "", description: "Do not abandon your goal in fear of condemnation, because as soon as the goal is achieved, the opinion of the condemners changes.", author: ""),
        .init(title: "", description: "The most intelligent person is the one who does not get into ego when success is achieved and does not get immersed in sorrow in failure.", author: ""),
        .init(title: "", description: "Just as a man abandons chronic clothes and wears other new clothes, the living soul abandons the old bodies and attains other new bodies.", author: ""),
        .init(title: "", description: "Negative thoughts are certain to come, but it depends on you, whether you give them importance or keep on focusing on your positive thoughts.", author: ""),
        .init(title: "", description: "A person who gives up all desires, he gets peace.", author: ""),
        .init(title: "", description: "Every wise man should give up anger and greed because it leads to the fall of the soul.", author: ""),
        .init(title: "", description: "What is yours will be together, even if it is a whole universe to take it away.", author: ""),
        .init(title: "", description: "Always remember, the best days have to be fought with bad days.", author: ""),
        .init(title: "", description: "The greatest source of inspiration is your own thoughts, so think big and always inspire yourself for as much as possible.", author: ""),
        .init(title: "", description: "Despite doing good deeds, people will only remember your evils. So don't pay attention to what people say, you just keep doing your work.", author: ""),
        .init(title: "", description: "There are three gates of hell – lust, anger, and greed.", author: ""),
        .init(title: "", description: "I give knowledge to those who are always connected to me and those who love me.", author: ""),
        .init(title: "", description: "No one gets anything more than time and luck.", author: ""),
        .init(title: "", description: "Human beings are made by their own faith, they become what they believe.", author: ""),
        .init(title: "", description: "By constant effort, the restless mind can be subdued.", author: ""),
        .init(title: "", description: "Only a friend and someone's enemy is the enemy.", author: ""),
        .init(title: "", description: "There is no greater answer than to remain silent and there is no greater punishment than forgiving.", author: ""),
        .init(title: "", description: "It's foolish to lose time in what's outside of your purview.", author: ""),
        .init(title: "", description: "The donation which is given to a needy person without any doubt, is the true charity.", author: ""),
        .init(title: "", description: "The other name of life is conflict.", author: ""),
        .init(title: "", description: "Just as the fire tests the gold, the trouble is to a brave man.", author: ""),
        .init(title: "", description: "I should not be proud that I will not need anyone and it should not be the same that everyone will need me.", author: ""),
        .init(title: "", description: "A person who pays attention to karma only by renouncing the desire of fruit, he definitely succeeds in life.", author: ""),
        .init(title: "", description: "Help everyone, but do not expect anyone, because only God can give the right value of service.", author: ""),
        .init(title: "", description: "Just as a boat is the only way to cross the sea, truth is a ladder to go to heaven.", author: ""),
        .init(title: "", description: "True friendships give half the sorrow and double the happiness.", author: ""),
        .init(title: "", description: "It is better to be silent as much as possible, because most of the sins make a person feel his tongue.", author: ""),
        .init(title: "", description: "Change is the law of the world, with time everything in the world follows the law of change.", author: ""),
        .init(title: "", description: "Why to suffer on what has passed, why to be arrogant on what is there, and why to fascinate the one who is going to come.", author: ""),
        .init(title: "", description: "Free from all thoughts of 'I' and 'mine', man finds absolute peace.", author: ""),
        .init(title: "", description: "Death is as sure for that which is born, as birth is for that which is dead. Therefore grieve not for what is inevitable.", author: ""),
        .init(title: "", description: "Happiness is a state of mind and has nothing to do with the external world.", author: ""),
        .init(title: "", description: "Make it easy for yourself. Get organized and live in the moment. Your day-to-day activities should not steal your happiness.", author: ""),
        .init(title: "", description: "Thus the Gita places human destiny entirely in human hands. Its world is not deterministic, but neither is it an expression of blind chance: we shape ourselves and our world by what we believe and think and act on, whether for good or for ill.", author: ""),
        .init(title: "", description: "The happiness which comes from long practice, which leads to the end of suffering, which at first is like poison, but at last like nectar – this kind of happiness arises from the serenity of one's own mind.", author: ""),
        .init(title: "", description: "Self-knowledge turns to ash all actions of dualities on your mind and brings you inner peace.", author: ""),
        .init(title: "", description: "The key to happiness is the reduction of desires.", author: ""),
        .init(title: "", description: "A person can rise through the efforts of his own mind; or draw himself down, in the same manner. Because each person is his own friend or enemy.", author: ""),
        .init(title: "", description: "Man is made by his beliefs. As he believes so he is.", author: ""),
        .init(title: "", description: "All happiness in the material world has a beginning and an end, but happiness in Krishna is unlimited, and there is no end.", author: ""),
        .init(title: "", description: "Through constant effort over many lifetimes, a person becomes purified of all selfish desires and attains the supreme goal of life.", author: ""),
        .init(title: "", description: "You grieve for those who should not be grieved for, Yet you speak wise words. Neither for the dead nor those alive do the wise grieve for.", author: ""),
        .init(title: "", description: "Meet this transient world with neither grasping nor fear, trust the unfolding of life and you will attain true serenity.", author: ""),
        .init(title: "", description: "The embodied soul is eternal in existence, indestructible, and infinite, only the material body is factually perishable.", author: ""),
        .init(title: "", description: "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.", author: ""),
        .init(title: "", description: "Causes and results, including emotional opposites, are things that come and go. This knowledge helps you endure them all.", author: ""),
        .init(title: "", description: "Wherever the mind wanders, restless and diffuse in its search for satisfaction without, lead it within; train it to rest in the Self.", author: ""),
        .init(title: "", description: "There are three gates to this self-destructive hell: lust, anger, and greed. Renounce these three.", author: ""),
        .init(title: "", description: "To refrain from selfish acts is one kind of renunciation, called sannyasa; to renounce the fruit of action is another, called Tyaga.", author: ""),
        .init(title: "", description: "Some people spread happiness wherever they go, others create happiness wherever they go!", author: ""),
        .init(title: "", description: "Death is no more traumatic than taking off an old coat.", author: ""),
        .init(title: "", description: "Perform all work carefully, guided by compassion.", author: ""),
        .init(title: "", description: "Some perceive God in the heart by the intellect through meditation; others by the yoga of knowledge; and others by the yoga of work. Some, however, do not understand Brahman, but having heard from others, take to worship. They also transcend death by their firm faith in what they have heard.", author: ""),
        .init(title: "", description: "Be aware of me always, adore me, make every act an offering to me, and you shall come to me; this I promise; for you are dear to me.", author: ""),
        .init(title: "", description: "Those established in Self-realization control their senses instead of letting their senses control them.", author: ""),
        .init(title: "", description: "Left to itself, the mind goes on repeating the same old habitual patterns of personality. By training the mind, however, anyone can learn to step in and change old ways of thinking; that is the central principle of yoga.", author: ""),
        .init(title: "", description: "It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.", author: ""),
        .init(title: "", description: "Seek refuge in the attitude of detachment and you will amass the wealth of spiritual awareness. Those who are motivated only by a desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.", author: ""),
        .init(title: "", description: "Without ego-involvement and without getting entangled in whether things work out the way we want; only then will we not fall into the terrible net of karma. We cannot hope to escape karma by refraining from our duties: even to survive in the world, we must act.", author: ""),
        .init(title: "", description: "When consciousness is unified, however, all vain anxiety is left behind. There is no cause for worry, whether things go well or ill.", author: ""),
        .init(title: "", description: "No one who does good work will ever come to a bad end, either here or in the world to come.", author: ""),
        .init(title: "", description: "Lust, anger, and greed are the three gates to self-destructive hell.", author: ""),
        .init(title: "", description: "There is neither this world, nor the world beyond, nor happiness for the one who doubts.", author: ""),
        .init(title: "", description: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.", author: ""),
        .init(title: "", description: "The soul is neither born nor does it die.", author: ""),
        .init(title: "", description: "Whatever happened, happened for the good. Whatever is happening, is happening for the good. Whatever will happen, will also happen for the good.", author: ""),
        .init(title: "", description: "While seeing or hearing, touching or smelling; eating, moving about, or sleeping; breathing or speaking, letting go or holding on, even opening or closing the eyes, they understand that these are only the movements of the senses among sense objects.", author: ""),
        .init(title: "", description: "Change is the law of the universe. You can be a millionaire or a pauper in an instant.", author: ""),
        .init(title: "", description: "Earth, water, fire, air, akasha, mind, intellect, and ego – these are the eight divisions of my prakriti.", author: ""),
        .init(title: "", description: "Cultivate vigor, patience, will, purity; avoid malice and pride.", author: ""),
        .init(title: "", description: "Those who are tamasic draw their pleasures from sleep, indolence, and intoxication. Both in the beginning and in the end, this happiness is a delusion.", author: ""),
        .init(title: "", description: "We ourselves are responsible for what happens to us, whether or not we can understand how. It follows that we can change what happens to us by changing ourselves; we can take our destiny into our own hands.", author: ""),
        .init(title: "", description: "The person is the same; he is simply experiencing the play of the gunas. As long as he identifies with his body and mind, he is at the mercy of this play.", author: ""),
        .init(title: "", description: "The rajasic person is full of energy; the tamasic person is sluggish, indifferent, insensitive; the sattvic person, calm, resourceful, compassionate, and selfless. Yet all three are always present at some level of awareness, and their proportions change: their interplay is the dynamics of personality.", author: ""),
        .init(title: "", description: "When your mind has overcome the confusion of duality, you will attain the state of holy indifference to things you hear and things you have heard.", author: ""),
        .init(title: "", description: "The struggle for self-mastery that every human being must wage if he or she is to emerge from life victorious.", author: ""),
        .init(title: "", description: "Be fearless and pure; never waver in your determination or your dedication to the spiritual life. Give freely. Be self-controlled, sincere, truthful, loving, and full of the desire to serve.", author: ""),
        .init(title: "", description: "His judgment will be better and his vision clear if he is not emotionally entangled in the outcome of what he does.", author: ""),
        .init(title: "", description: "For one who has conquered his mind, a mind is best of friends, but for one who has failed to do so, a mind is the greatest enemy.", author: ""),
        .init(title: "", description: "Happiness from the senses seems like nectar initially, but it is bitter as poison in the end.", author: ""),
        .init(title: "", description: "Set thy heart upon thy work, but never on its reward.", author: ""),
        .init(title: "", description: "He who is content with whatever comes, without attachment, not disappointed when he gets nothing, is wise.", author: ""),
        .init(title: "", description: "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.", author: ""),
        .init(title: "", description: "As a strong wind sweeps away a boat on the water, even one of the roaming world of the senses on which the mind focuses can carry away a man's intellect.", author: ""),
        .init(title: "", description: "One who sees inaction in action, and action in inaction, is intelligent among men.", author: ""),
        .init(title: "", description: "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.", author: ""),
        .init(title: "", description: "There is neither this world nor the world beyond nor happiness for the one who doubts.", author: ""),
        .init(title: "", description: "A person can rise through the efforts of his own mind; or draw himself down in the same manner. Because each person is his own friend or enemy.", author: ""),
        .init(title: "", description: "Perform your obligatory duty because action is indeed better than inaction.", author: ""),
        .init(title: "", description: "One who performs his duty without attachment, surrendering the results unto the Supreme Lord, is unaffected by sinful action.", author: ""),
        .init(title: "", description: "The wise should work without attachment, for the welfare of the society.", author: ""),
        .init(title: "", description: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions.", author: ""),
        .init(title: "", description: "Whatever you do, whatever you eat, whatever you offer or give away, and whatever austerities you perform – do that, O son of Kunti, as an offering to Me.", author: ""),
        .init(title: "", description: "When your intellect transcends the mire of delusion, then you will attain to dispassion of what has been heard and what is yet to be heard.", author: ""),
        .init(title: "", description: "Actions do not cling to me because I am not attached to their results. Those who understand this and practice it live in freedom.", author: ""),
        .init(title: "", description: "As the ignorant perform their duties with attachment to results, the learned may similarly act, but without attachment, for the sake of leading people on the right path.", author: ""),
        .init(title: "", description: "Let your aim be the good of all. Then carry out your task in life with an unswerving devotion to truth, refusing to yield to selfish desires or to the errors of human nature.", author: ""),
        .init(title: "", description: "One who is not disturbed by happiness and distress and is steady in both is certainly eligible for liberation.", author: ""),
        .init(title: "", description: "One who has wisdom and discernment is always calm and collected; such a person is in true knowledge.", author: ""),
        .init(title: "", description: "The truly wise mourn neither for the living nor for the dead.", author: ""),
        .init(title: "", description: "There is nothing in the world as purifying as knowledge; one who has attained purity of heart through prolonged practice of karma yoga automatically sees the light of truth in the self in course of time.", author: ""),
        .init(title: "", description: "When you move amidst the world of sense, free from attachment and aversion alike, there comes the peace in which all sorrows end, and you live in the wisdom of the self.", author: ""),
        .init(title: "", description: "A person is said to be established in self-realization and is called a yogi when he is fully satisfied by virtue of acquired knowledge and realization.", author: ""),
        .init(title: "", description: "He who is able to resist the force of desire and anger before he quits his body is a yogi and is happy.", author: ""),
        .init(title: "", description: "The disunited mind is far from wise; how can it meditate? How can it be at peace? When you know no peace, how can you know joy?", author: ""),
        .init(title: "", description: "When a person responds to the joys and sorrows of others as if they were his own, he has attained the highest state of spiritual union.", author: ""),
        .init(title: "", description: "This divine wisdom is a direct perception of the truth, much superior to any indirect knowledge of the scriptures or hearsay.", author: ""),
        .init(title: "", description: "He who sees me everywhere and sees everything in me will not be lost to me, and I will not be lost to him.", author: ""),
        .init(title: "", description: "You have the right to work but never to the fruit of work.", author: ""),
        .init(title: "", description: "It is better to strive in one's own dharma than to succeed in the dharma of another.", author: ""),
        .init(title: "", description: "A disciplined mind brings happiness.", author: ""),
        .init(title: "", description: "The wise unify their consciousness and abandon attachment to the fruits of action.", author: ""),
        .init(title: "", description: "Sever the ignorant doubt in your heart with the sword of self-knowledge. Observe your discipline. Arise.", author: ""),
        .init(title: "", description: "Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.", author: ""),
        .init(title: "", description: "When a person is devoted to something with complete faith, I unify his faith in that.", author: ""),
        .init(title: "", description: "Reshape yourself through the power of your will; never let yourself be degraded by self-will.", author: ""),
        .init(title: "", description: "Man is made by his belief. As he believes, so he is.", author: ""),
        .init(title: "", description: "The ignorant work for their own profit, the wise work for the welfare of the world.", author: ""),
        .init(title: "", description: "There are three gates to this self-destructive hell: lust, anger, and greed. Renounce these three.", author: ""),
        .init(title: "", description: "That one is dear to me who runs not after the pleasant or away from the painful, grieves not, lusts not, but lets things come and go as they happen.", author: ""),
        .init(title: "", description: "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.", author: ""),
        .init(title: "", description: "The truly wise mourn neither for those who are living, nor for those who have passed away.", author: ""),
        .init(title: "", description: "Man is made by his belief. As he believes, so he is.", author: ""),
        .init(title: "", description: "The mind alone is one's friend as well as one's enemy.", author: ""),
        .init(title: "", description: "Death is as sure for that which is born, as birth is for that which is dead. Therefore grieve not for what is inevitable.", author: ""),
        .init(title: "", description: "One who sees inaction in action, and action in inaction, is intelligent among men.", author: ""),
        .init(title: "", description: "Krishna says: Arjuna, I am the taste of pure water and the radiance of the sun and moon. I am the sacred word and the sound heard in air, and the courage of human beings. I am the sweet fragrance in the earth and the radiance of fire; I am the life in every creature and the striving of the spiritual aspirant.", author: ""),
        .init(title: "", description: "When a man dwells on the pleasure of sense, attraction for them arises in him. From attraction arises desire, the lust of possession, and this leads to passion, to anger. From passion comes confusion of mind, then loss of remembrance, the forgetting of duty. From this loss comes the ruin of reason, and the ruin of reason leads man to destruction.", author: ""),
        .init(title: "", description: "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions.", author: ""),
        .init(title: "", description: "The spirit is beyond destruction. No one can bring an end to spirit which is everlasting.", author: ""),
        .init(title: "", description: "In the dark night of all beings awakes to Light the tranquil man. But what is day to other beings is night for the sage who sees.", author: ""),
        .init(title: "", description: "Through selfless service, you will always be fruitful and find the fulfillment of your desires.", author: ""),
        .init(title: "", description: "The soul can never be cut into pieces by any weapon nor burned by fire, nor moistened by water, nor withered by the wind.", author: "")
    ]
}
